{
 "title": "02 - Throughput",
 "description": "Java client Kafka Producer metrics",
 "tags": [ "producer" ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(jvm_info{cluster_type=~\"streams|producers|consumers\"},cluster_id)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kafka_producer_app_info_start_time_ms{cluster_id=~\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Outgoing Messages / second (client)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(kafka_producer_record_send_total{cluster_id=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Outgoing Byte Rate (client)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(kafka_producer_outgoing_byte_total{cluster_id=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Outgoing messages / second (topic)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_producer_topic_record_send_total{cluster_id=~\"$cluster\", instance=~\"$instance\", topic=~\".+\"}[$__rate_interval])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Outgoing Byte Rate (topic)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_producer_topic_byte_total{cluster_id=~\"$cluster\", instance=~\"$instance\", topic=~\".+\"}[$__rate_interval])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}