{
 "title": "01 - Overview",
 "tags": [
  "kafka_cluster",
  "kafka"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(jvm_info{cluster_type=\"kafka\"}, cluster_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Online Brokers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_value{cluster_id=~\"$cluster\", name=\"LeaderCount\"})"
    }
   ]
  },
  {
   "title": "Online Controllers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_value{cluster_id=~\"$cluster\", name=\"ActiveControllerCount\"})"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_value{cluster_id=~\"$cluster\", name=\"ActiveControllerCount\"})"
    }
   ]
  },
  {
   "title": "Active Controller Id",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, kafka_server_raft_metrics_current_leader{cluster_id=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_value{cluster_id=~\"$cluster\", name=\"PartitionCount\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_value{cluster_id=~\"$cluster\", name=\"UnderReplicatedPartitions\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_value{cluster_id=~\"$cluster\", name=\"OfflinePartitionsCount\"})"
    }
   ]
  },
  {
   "title": "Node Controller State",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "max by(instance, state, node_id) (kafka_server_raft_metrics_current_state{cluster_id=~\"$cluster\", state=~\"(.+)\"} + on (cluster_id, instance) group_left(node_id) (0 * kafka_server_app_info_version{cluster_id=~\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Partitions / Leaders / Under Replicas",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum by(instance, node_id) (kafka_server_replicamanager_value{cluster_id=~\"$cluster\", name=\"PartitionCount\",} + on (cluster_id, instance) group_left(node_id) (0 * kafka_server_app_info_version{cluster_id=~\"$cluster\"}))"
    },
    {
     "expr": "sum by(instance) (kafka_server_replicamanager_value{cluster_id=~\"$cluster\", name=\"LeaderCount\"})"
    },
    {
     "expr": "sum by(instance) (kafka_server_replicamanager_value{cluster_id=~\"$cluster\", name=\"UnderReplicatedPartitions\"})"
    }
   ]
  },
  {
   "title": "log size by node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (kafka_log_log_value{cluster_id=~\"$cluster\", name=\"Size\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}