{
 "title": "03 - Brokers",
 "tags": [
  "kafka_cluster",
  "kafka"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(jvm_info{cluster_type=\"kafka\"}, cluster_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Online Brokers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_value{name=\"LeaderCount\",})"
    }
   ]
  },
  {
   "title": "Online Controllers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_value{name=\"ActiveControllerCount\",})"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_value{name=\"ActiveControllerCount\",})"
    }
   ]
  },
  {
   "title": "Active Controller Id",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, kafka_server_raft_metrics_current_leader{})"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_value{name=\"PartitionCount\",})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_value{name=\"UnderReplicatedPartitions\",})"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_value{name=\"OfflinePartitionsCount\",})"
    }
   ]
  },
  {
   "title": "Messages In",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(instance,job)(kafka_server_brokertopicmetrics_oneminuterate{name=\"MessagesInPerSec\",topic=\"\"})"
    }
   ]
  },
  {
   "title": "Bytes In",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum without(instance,job)(kafka_server_brokertopicmetrics_oneminuterate{name=\"BytesInPerSec\",topic=\"\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum without(instance,job)(kafka_server_brokertopicmetrics_oneminuterate{name=\"BytesOutPerSec\",topic=\"\"})"
    }
   ]
  },
  {
   "title": "Messages In Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(job)(kafka_server_brokertopicmetrics_oneminuterate{name=\"MessagesInPerSec\",topic=\"\"} > 0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum without(job)(kafka_server_brokertopicmetrics_oneminuterate{name=\"BytesInPerSec\",topic=\"\"} > 0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum without(job)(kafka_server_brokertopicmetrics_oneminuterate{name=\"BytesOutPerSec\",topic=\"\"} > 0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(instance,job)(kafka_server_brokertopicmetrics_oneminuterate{name=\"MessagesInPerSec\",topic!~\"(_)+confluent.+\",topic!=\"\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum without(instance,job)(kafka_server_brokertopicmetrics_oneminuterate{name=\"BytesInPerSec\",topic!~\"(_)+confluent.+\",topic!=\"\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum without(instance,job)(kafka_server_brokertopicmetrics_oneminuterate{name=\"BytesOutPerSec\",topic!~\"(_)+confluent.+\",topic!=\"\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka log size by topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_log_log_value{name=\"Size\", topic!~\"(_)+confluent.+\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka log size by broker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (kafka_log_log_value{instance=~\".+\", name=\"Size\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Underreplicated partitions by topic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (topic)(kafka_cluster_partition_value{name=\"UnderReplicated\",topic!~\"(_)+confluent.+\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "ISR expands by instance",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_oneminuterate{instance=~\".+\", name=\"IsrExpandsPerSec\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Partitions / Leaders / Under Replicas",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by(instance, node_id) (kafka_server_replicamanager_value{instance=~\".+\", name=\"PartitionCount\",} + on (cluster_id, instance) group_left(node_id) (0 * kafka_server_app_info_version))"
    },
    {
     "expr": "sum by(instance) (kafka_server_replicamanager_value{instance=~\".+\", name=\"LeaderCount\",})"
    },
    {
     "expr": "sum by(instance) (kafka_server_replicamanager_value{instance=~\".+\", name=\"UnderReplicatedPartitions\",})"
    }
   ]
  },
  {
   "title": "Purgatory Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(instance,job)(kafka_server_delayedoperationpurgatory_value{name=\"PurgatorySize\",delayedOperation=~\"(.+)\"})",
     "legendFormat": "{{delayedOperation}}"
    }
   ]
  }
 ]
}