{
 "title": "05 - Network",
 "description": "Apache Kafka resource usage and throughput",
 "tags": [
  "kafka_cluster",
  "kafka"
 ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(jvm_info{cluster_type=\"kafka\"}, cluster_id)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_info{cluster_type=\"kafka\", cluster_id=\"$cluster\"}, instance)"
    }
   },
   {
    "name": "listener",
    "label": "listener",
    "query": {
     "query": "label_values(kafka_server_socket_server_metrics_select_rate{cluster_type=\"kafka\", cluster_id=\"$cluster\", instance=~\"$instance\"}, listener)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "IO Selection Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg (kafka_server_socket_server_metrics_select_rate{cluster_id=~\"$cluster\", instance=~\"$instance\", listener=~\"$listener\"}) by (instance, listener)",
     "legendFormat": "{{instance}} ({{listener}})"
    }
   ]
  },
  {
   "title": "IO Duration / Select Call",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg (kafka_server_socket_server_metrics_io_time_ns_avg{cluster_id=~\"$cluster\", instance=~\"$instance\", listener=~\"$listener\"}) by (instance, listener)",
     "legendFormat": "{{instance}} ({{listener}})"
    }
   ]
  },
  {
   "title": "1 - IO Ratio - IO Wait Ratio",
   "type": "timeseries",
   "description": "1 indicates that the broker is the bottleneck in relation to the clients.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg (1 - kafka_server_socket_server_metrics_io_ratio{cluster_id=~\"$cluster\", instance=~\"$instance\", listener=~\"$listener\"} - kafka_server_socket_server_metrics_io_wait_ratio{cluster_id=~\"$cluster\", instance=~\"$instance\", listener=~\"$listener\"}) by (instance, listener)",
     "legendFormat": "{{instance}} ({{listener}})"
    }
   ]
  },
  {
   "title": "IO Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg (kafka_server_socket_server_metrics_io_ratio{cluster_id=~\"$cluster\", instance=~\"$instance\", listener=~\"$listener\"}) by (instance, listener)",
     "legendFormat": "{{instance}} ({{listener}})"
    }
   ]
  },
  {
   "title": "IO Wait Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg (kafka_server_socket_server_metrics_io_wait_ratio{cluster_id=~\"$cluster\", instance=~\"$instance\", listener=~\"$listener\"}) by (instance,listener)",
     "legendFormat": "{{instance}} ({{listener}})"
    }
   ]
  }
 ]
}