---
lowercaseOutputName: true
lowercaseOutputLabelNames: true
# whitelistObjectNames:
#   - "kafka.server:*"
#   - "kafka.network:*"
# blacklistObjectNames:
#   - "kafka.admin.client:*"
#   - "kafka.consumer:type=*,id=*"
#   - "kafka.producer:type=*,id=*"
#   - "kafka.*:type=kafka-metrics-count,*"
rules:
  - pattern: ".*"
  # # "kafka.consumer:type=app-info,client-id=*"
  # # "kafka.producer:type=app-info,client-id=*"
  # - pattern: "kafka.(.+)<type=app-info, client-id=(.+)><>(.+): (.+)"
  #   value: 1
  #   name: kafka_$1_app_info
  #   labels:
  #     client_type: $1
  #     client_id: $2
  #     $3: $4
  #   type: UNTYPED
  # # "kafka.consumer:type=consumer-metrics,client-id=*, protocol=*, cipher=*"
  # # "kafka.consumer:type=type=consumer-fetch-manager-metrics,client-id=*, topic=*, partition=*"
  # # "kafka.producer:type=producer-metrics,client-id=*, protocol=*, cipher=*"
  # - pattern: "kafka.(.+)<type=(.+), (.+)=(.+), (.+)=(.+), (.+)=(.+)><>(.+):"
  #   name: kafka_$1_$2_$9
  #   type: GAUGE
  #   labels:
  #     client_type: $1
  #     $3: "$4"
  #     $5: "$6"
  #     $7: "$8"